apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-downloader
data:
  script.sh: |
    DIRECTORY_NAME=$(date --date="$(date +%Y-%m-15) -1 month" +'data_%Y-%m')
    echo $DIRECTORY_NAME
    aws s3 cp s3://openshift-metrics/$DIRECTORY_NAME/ /data --endpoint-url=https://s3.us-east-005.backblazeb2.com --recursive
